#!/usr/bin/env bash
# Deploy RAGFlow on a Linux cloud VM (recommended: 16GB+ RAM, 50GB+ disk).
# Run this script ON the server, not on your Mac.
#
# Usage (bundled MySQL + Redis):
#   ./scripts/setup-ragflow-server.sh
#
# Usage (your own MySQL + Redis — config file, recommended):
#   cp scripts/ragflow-external-deps.env.example scripts/ragflow-external-deps.env
#   # edit scripts/ragflow-external-deps.env
#   ./scripts/setup-ragflow-server.sh
#
# Or export env vars before running (see README).
# MySQL on the same host as Docker: MYSQL_HOST=host.docker.internal
# Prepare MySQL first: CREATE DATABASE rag_flow; grant user utf8mb4 access.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RAGFLOW_DIR="${RAGFLOW_DIR:-$ROOT/../ragflow}"
DEPS_ENV="${RAGFLOW_DEPS_ENV:-$ROOT/scripts/ragflow-external-deps.env}"
TIKTOKEN_URL="https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken"
TIKTOKEN_CACHE_KEY="9b5ad71b2ce5302211f9c61530b329a4922fc6a4"

if [[ -f "$DEPS_ENV" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$DEPS_ENV"
  set +a
  echo "==> Loaded external deps from $DEPS_ENV"
fi

_set_env_var() {
  local file="$1" key="$2" value="$3"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$file"
  else
    echo "${key}=${value}" >>"$file"
  fi
}

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "Error: This script is for Linux servers. For local Mac dev use ./scripts/setup-ragflow.sh" >&2
  exit 1
fi

if ! command -v docker >/dev/null 2>&1 || ! docker info >/dev/null 2>&1; then
  echo "Error: Install Docker 24+ and start the daemon first." >&2
  echo "  https://docs.docker.com/engine/install/" >&2
  exit 1
fi

USE_EXTERNAL_MYSQL=0
USE_EXTERNAL_REDIS=0
[[ -n "${MYSQL_HOST:-}" ]] && USE_EXTERNAL_MYSQL=1
[[ -n "${REDIS_HOST:-}" ]] && USE_EXTERNAL_REDIS=1

if [[ "$USE_EXTERNAL_MYSQL" -eq 1 || "$USE_EXTERNAL_REDIS" -eq 1 ]]; then
  if [[ "$USE_EXTERNAL_MYSQL" -eq 1 && -z "${MYSQL_PASSWORD:-}" ]]; then
    echo "Error: MYSQL_HOST is set; also set MYSQL_PASSWORD (and usually MYSQL_USER, MYSQL_DBNAME)." >&2
    exit 1
  fi
  if [[ "$USE_EXTERNAL_REDIS" -eq 1 && -z "${REDIS_PASSWORD:-}" ]]; then
    echo "Error: REDIS_HOST is set; also set REDIS_PASSWORD." >&2
    exit 1
  fi
fi

current="$(sysctl -n vm.max_map_count 2>/dev/null || echo 0)"
if [[ "$current" -lt 262144 ]]; then
  echo "==> Setting vm.max_map_count=262144 (required for Elasticsearch)"
  sudo sysctl -w vm.max_map_count=262144
  if ! grep -q 'vm.max_map_count' /etc/sysctl.conf 2>/dev/null; then
    echo 'vm.max_map_count=262144' | sudo tee -a /etc/sysctl.conf >/dev/null
  fi
fi

if [[ ! -d "$RAGFLOW_DIR/.git" ]]; then
  echo "==> Cloning RAGFlow into $RAGFLOW_DIR"
  git clone --depth 1 https://github.com/infiniflow/ragflow.git "$RAGFLOW_DIR"
else
  echo "==> RAGFlow already cloned at $RAGFLOW_DIR"
fi

ENV_FILE="$RAGFLOW_DIR/docker/.env"
if [[ -f "$ENV_FILE" ]]; then
  sed -i 's/^EXPOSE_MYSQL_PORT=3306/EXPOSE_MYSQL_PORT=5455/' "$ENV_FILE" 2>/dev/null || true
fi

if [[ "$USE_EXTERNAL_MYSQL" -eq 1 ]]; then
  echo "==> Using external MySQL at ${MYSQL_HOST}:${MYSQL_PORT:-3306}"
  _set_env_var "$ENV_FILE" MYSQL_HOST "$MYSQL_HOST"
  _set_env_var "$ENV_FILE" MYSQL_PORT "${MYSQL_PORT:-3306}"
  _set_env_var "$ENV_FILE" MYSQL_USER "${MYSQL_USER:-root}"
  _set_env_var "$ENV_FILE" MYSQL_PASSWORD "$MYSQL_PASSWORD"
  _set_env_var "$ENV_FILE" MYSQL_DBNAME "${MYSQL_DBNAME:-rag_flow}"
fi

if [[ "$USE_EXTERNAL_REDIS" -eq 1 ]]; then
  echo "==> Using external Redis at ${REDIS_HOST}:6379 (RAGFlow uses logical db 1)"
  _set_env_var "$ENV_FILE" REDIS_HOST "$REDIS_HOST"
  _set_env_var "$ENV_FILE" REDIS_PASSWORD "$REDIS_PASSWORD"
  if [[ -n "${REDIS_USERNAME:-}" ]]; then
    _set_env_var "$ENV_FILE" REDIS_USERNAME "$REDIS_USERNAME"
  fi
fi

TIKTOKEN_CACHE_DIR="$RAGFLOW_DIR/docker/tiktoken-cache"
mkdir -p "$TIKTOKEN_CACHE_DIR"
if [[ ! -f "$TIKTOKEN_CACHE_DIR/$TIKTOKEN_CACHE_KEY" ]]; then
  echo "==> Preloading tiktoken cache..."
  curl -fsSL -o "$TIKTOKEN_CACHE_DIR/$TIKTOKEN_CACHE_KEY" "$TIKTOKEN_URL"
fi

OVERRIDE_FILE="$RAGFLOW_DIR/docker/docker-compose.agentflow.override.yml"

DEPENDS_ON_BLOCK=""
MYSQL_PROFILE_BLOCK=""
REDIS_PROFILE_BLOCK=""
if [[ "$USE_EXTERNAL_MYSQL" -eq 1 || "$USE_EXTERNAL_REDIS" -eq 1 ]]; then
  DEPENDS_ON_BLOCK="    depends_on: {}"
fi
if [[ "$USE_EXTERNAL_MYSQL" -eq 1 ]]; then
  MYSQL_PROFILE_BLOCK="
  mysql:
    profiles: [\"bundled-only\"]"
fi
if [[ "$USE_EXTERNAL_REDIS" -eq 1 ]]; then
  REDIS_PROFILE_BLOCK="
  redis:
    profiles: [\"bundled-only\"]"
fi

cat > "$OVERRIDE_FILE" <<EOF
# Generated by agentFlowContainer/scripts/setup-ragflow-server.sh
services:
  ragflow-cpu:
    command:
      - --enable-adminserver
${DEPENDS_ON_BLOCK}
    volumes:
      - ./tiktoken-cache/${TIKTOKEN_CACHE_KEY}:/ragflow/${TIKTOKEN_CACHE_KEY}:ro${MYSQL_PROFILE_BLOCK}${REDIS_PROFILE_BLOCK}
EOF

if [[ "$USE_EXTERNAL_MYSQL" -eq 1 ]]; then
  echo ""
  echo "Ensure external MySQL has database + user (run on your MySQL server):"
  echo "  CREATE DATABASE IF NOT EXISTS ${MYSQL_DBNAME:-rag_flow} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  echo "  CREATE USER IF NOT EXISTS '${MYSQL_USER:-root}'@'%' IDENTIFIED BY '...';"
  echo "  GRANT ALL ON ${MYSQL_DBNAME:-rag_flow}.* TO '${MYSQL_USER:-root}'@'%';"
  echo "  FLUSH PRIVILEGES;"
  echo "RAGFlow will create tables on first boot."
  echo ""
fi

echo "==> Starting RAGFlow (this may take several minutes on first pull)..."
cd "$RAGFLOW_DIR/docker"
docker compose -f docker-compose.yml -f docker-compose.agentflow.override.yml up -d

server_ip="$(curl -fsSL -m 5 ifconfig.me 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}' || echo '<server-ip>')"

echo ""
echo "RAGFlow is starting. Monitor:"
echo "  docker logs -f \$(docker ps --filter name=ragflow -q | head -1)"
echo ""
echo "When healthy (no 'Killed' in logs), open:"
echo "  http://${server_ip}"
echo ""
echo "Firewall: allow inbound TCP 80 (UI) and 9380 (API) if needed."
if [[ "$USE_EXTERNAL_MYSQL" -eq 0 ]]; then
  echo "Do NOT expose bundled MySQL (5455) to the public internet."
fi
if [[ "$USE_EXTERNAL_REDIS" -eq 0 ]]; then
  echo "Do NOT expose bundled Redis (6379) to the public internet."
fi
echo ""
echo "In agentFlowContainer .env on your dev machine:"
echo "  RAG_BACKEND=ragflow"
echo "  RAGFLOW_BASE_URL=http://${server_ip}"
echo "  RAGFLOW_API_KEY=<from RAGFlow UI → Settings → API>"
