#!/usr/bin/env bash
# Install and start RAGFlow locally (separate from agentFlowContainer stack).
# For 8GB Macs this is unreliable — prefer a cloud VM: ./scripts/setup-ragflow-server.sh
#
# Usage:
#   ./scripts/setup-ragflow.sh          # clone + docker compose up
#   ./scripts/setup-ragflow.sh --clone-only
#
# Prerequisites: Docker 24+, Compose v2.26+, RAM >= 16GB, disk >= 50GB
# Linux only: sudo sysctl -w vm.max_map_count=262144

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RAGFLOW_DIR="${RAGFLOW_DIR:-$ROOT/../ragflow}"
CLONE_ONLY=0

for arg in "$@"; do
  case "$arg" in
    --clone-only) CLONE_ONLY=1 ;;
    -h|--help)
      echo "Usage: $0 [--clone-only]"
      echo "  RAGFLOW_DIR  override install path (default: ../ragflow)"
      exit 0
      ;;
  esac
done

if ! command -v docker >/dev/null 2>&1; then
  echo "Error: Docker is required." >&2
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  echo "Error: Cannot connect to the Docker daemon." >&2
  echo "  macOS: open Docker Desktop and wait until it shows 'Docker is running', then re-run:" >&2
  echo "    $0" >&2
  echo "  Linux: sudo systemctl start docker" >&2
  exit 1
fi

if [[ "$(uname -s)" == "Linux" ]]; then
  current="$(sysctl -n vm.max_map_count 2>/dev/null || echo 0)"
  if [[ "$current" -lt 262144 ]]; then
    echo "Warning: vm.max_map_count=$current (< 262144). RAGFlow/ES may fail."
    echo "  Run: sudo sysctl -w vm.max_map_count=262144"
  fi
fi

if [[ ! -d "$RAGFLOW_DIR/.git" ]]; then
  echo "==> Cloning RAGFlow into $RAGFLOW_DIR"
  git clone --depth 1 https://github.com/infiniflow/ragflow.git "$RAGFLOW_DIR"
else
  echo "==> RAGFlow already cloned at $RAGFLOW_DIR"
fi

if [[ "$CLONE_ONLY" -eq 1 ]]; then
  exit 0
fi

ENV_FILE="$RAGFLOW_DIR/docker/.env"
_sed_inplace() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

if [[ -f "$ENV_FILE" ]]; then
  if grep -q '^EXPOSE_MYSQL_PORT=3306' "$ENV_FILE" 2>/dev/null; then
    if lsof -i :3306 -sTCP:LISTEN >/dev/null 2>&1; then
      echo "==> Port 3306 in use; setting EXPOSE_MYSQL_PORT=5455 in $ENV_FILE"
      _sed_inplace 's/^EXPOSE_MYSQL_PORT=3306/EXPOSE_MYSQL_PORT=5455/' "$ENV_FILE"
    fi
  fi

  # Elasticsearch needs ~8GB+ and OOMs on 8–16GB Macs. Prefer Infinity on low-memory hosts.
  host_ram_bytes="$(sysctl -n hw.memsize 2>/dev/null || echo 0)"
  if [[ "$host_ram_bytes" -gt 0 && "$host_ram_bytes" -lt 17179869184 ]]; then
    if ! grep -q '^DOC_ENGINE=infinity' "$ENV_FILE" 2>/dev/null; then
      echo "==> Host RAM < 16GB; switching DOC_ENGINE to infinity (lighter than Elasticsearch)"
      _sed_inplace 's/^DOC_ENGINE=.*/DOC_ENGINE=infinity/' "$ENV_FILE"
      _sed_inplace 's/^MEM_LIMIT=.*/MEM_LIMIT=2147483648/' "$ENV_FILE"
      _sed_inplace 's/^INFINITY_PSQL_PORT=5432/INFINITY_PSQL_PORT=15432/' "$ENV_FILE"
      _sed_inplace 's/^# MACOS=1/MACOS=1/' "$ENV_FILE"
    fi
  fi
fi

TIKTOKEN_URL="https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken"
TIKTOKEN_CACHE_KEY="9b5ad71b2ce5302211f9c61530b329a4922fc6a4"
TIKTOKEN_CACHE_DIR="$RAGFLOW_DIR/docker/tiktoken-cache"
mkdir -p "$TIKTOKEN_CACHE_DIR"
if [[ ! -f "$TIKTOKEN_CACHE_DIR/$TIKTOKEN_CACHE_KEY" ]]; then
  echo "==> Downloading tiktoken cache (container may not reach Azure)..."
  curl -fsSL -o "$TIKTOKEN_CACHE_DIR/$TIKTOKEN_CACHE_KEY" "$TIKTOKEN_URL"
fi

OVERRIDE_FILE="$RAGFLOW_DIR/docker/docker-compose.agentflow.override.yml"
cat > "$OVERRIDE_FILE" <<EOF
# Generated by agentFlowContainer/scripts/setup-ragflow.sh
services:
  ragflow-cpu:
    # Skip admin server (default compose adds --enable-adminserver) and datasync to save RAM.
    command:
      - --disable-datasync
    volumes:
      - ./tiktoken-cache/${TIKTOKEN_CACHE_KEY}:/ragflow/${TIKTOKEN_CACHE_KEY}:ro
EOF

echo "==> Starting RAGFlow (docker compose in $RAGFLOW_DIR/docker)"
cd "$RAGFLOW_DIR/docker"
docker compose -f docker-compose.yml -f docker-compose.agentflow.override.yml up -d

echo ""
echo "RAGFlow starting (first boot on Apple Silicon may take 3–5 minutes)."
echo "If the UI shows 502, wait then hard-refresh. On 8GB Macs:"
echo "  Docker Desktop → Settings → Resources → Memory: set to 6GB+"
echo "  Stop other heavy compose stacks to free RAM."
echo "Check logs:"
echo "  docker logs -f \$(docker ps --filter name=ragflow -q | head -1)"
echo ""
echo "When ready, open: http://localhost"
echo "Get API key: RAGFlow UI → Settings → API"
echo ""
echo "Then in agentFlowContainer .env:"
echo "  RAG_BACKEND=ragflow"
echo "  RAGFLOW_BASE_URL=http://localhost"
echo "  RAGFLOW_API_KEY=<your-key>"
